// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackWorkProject.WebUI.Data;

#nullable disable

namespace TrackWorkProject.WebUI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304140712_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Directorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Directorates");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Duty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.PersonelDuty", b =>
                {
                    b.Property<int>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonelId", "DutyId");

                    b.HasIndex("DutyId");

                    b.ToTable("PersonelDuty");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Duty", b =>
                {
                    b.HasOne("TrackWorkProject.WebUI.Entities.Directorate", "Directorate")
                        .WithMany("Duties")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directorate");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.PersonelDuty", b =>
                {
                    b.HasOne("TrackWorkProject.WebUI.Entities.Duty", "Duty")
                        .WithMany("PersonelDuties")
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackWorkProject.WebUI.Entities.Personel", "Personel")
                        .WithMany("PersonelDuties")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Directorate", b =>
                {
                    b.Navigation("Duties");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Duty", b =>
                {
                    b.Navigation("PersonelDuties");
                });

            modelBuilder.Entity("TrackWorkProject.WebUI.Entities.Personel", b =>
                {
                    b.Navigation("PersonelDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
